// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete.sql

package database

import (
	"context"
	"database/sql"
)

const deleteUsers = `-- name: DeleteUsers :execresult
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUsers)
}
