// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteChirp.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteChirp = `-- name: DeleteChirp :execresult
DELETE FROM chirps
where id = $1
`

func (q *Queries) DeleteChirp(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteChirp, id)
}
