// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revokeRefreshToken.sql

package database

import (
	"context"
	"database/sql"
)

const revokeRefreshToken = `-- name: RevokeRefreshToken :execresult
update refresh_tokens 
set revoked_at = NOW(), updated_at = NOW()
where token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeRefreshToken, token)
}
